# Generated by Django 5.1.6 on 2025-02-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetail_nickname_userdetail_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='profile',
        ),
    ]
