# Generated by Django 5.1.5 on 2025-03-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile/'),
        ),
    ]
