# Generated by Django 5.1.4 on 2025-03-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_userdetail_nickname_alter_userdetail_profile"),
        ("users", "0009_alter_userdetail_profile"),
    ]

    operations = []
