# Generated by Django 5.1.4 on 2025-03-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_merge_20250307_2156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="profile/default.jpg",
                max_length=500,
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
