# Generated by Django 5.1.6 on 2025-02-11 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('productCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('productCategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('convenientStoreName', models.IntegerField()),
                ('productPrice', models.IntegerField()),
                ('productImageUrl', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='Product_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
