# Generated by Django 5.1.6 on 2025-02-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_convenient_store_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlikes',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productlikes',
            old_name='userID',
            new_name='user',
        ),
    ]
