# Generated by Django 5.1.4 on 2025-02-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_alter_community_deadline"),
        ("product", "0007_rename_productid_productlikes_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="community",
            old_name="authorId",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="community",
            old_name="categoryId",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="community",
            name="productId",
        ),
        migrations.AddField(
            model_name="community",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="Community_products", to="product.product"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="communityContent",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="community",
            name="communityTitle",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="community",
            name="deadline",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
