# Generated by Django 5.1.4 on 2025-02-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasteContent', models.TextField()),
                ('priceContent', models.TextField()),
                ('convenienceContent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewImageUrl', models.URLField()),
            ],
        ),
    ]
