# Generated by Django 5.1.6 on 2025-02-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewImageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
