# Generated by Django 5.1.6 on 2025-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_reviewimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewImageUrl',
            field=models.ImageField(upload_to=''),
        ),
    ]
