# Generated by Django 5.1.6 on 2025-02-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_reviewimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewImageUrl',
            field=models.CharField(max_length=300),
        ),
    ]
