# Generated by Django 5.1.6 on 2025-02-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_review_reviewimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewImageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='review/'),
        ),
    ]
