# Generated by Django 5.1.6 on 2025-02-18 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_review_reviewimageurl'),
        ('users', '0008_userdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='authorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserDetail_reviews', to='users.userdetail'),
        ),
    ]
