# Generated by Django 5.1.4 on 2025-02-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0009_alter_review_authorid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewImageUrl",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
    ]
