# Generated by Django 5.1.6 on 2025-02-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_review_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='authorId',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewImageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
