# Generated by Django 5.1.6 on 2025-02-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_rename_authorid_review_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='productId',
            new_name='product',
        ),
    ]
