# Generated by Django 5.1.4 on 2025-02-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0010_alter_review_reviewimageurl"),
        ("review", "0011_rename_productid_review_product"),
    ]

    operations = []
