# Generated by Django 5.1.6 on 2025-02-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_merge_20250220_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrecommender',
            old_name='recommenderId',
            new_name='recommender',
        ),
        migrations.RenameField(
            model_name='reviewrecommender',
            old_name='reviewId',
            new_name='review',
        ),
    ]
