# Generated by Django 5.1.6 on 2025-02-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_rename_recommenderid_reviewrecommender_recommender_and_more'),
        ('users', '0008_userdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommender',
            field=models.ManyToManyField(blank=True, null=True, related_name='Review_recommender', through='review.ReviewRecommender', to='users.userdetail'),
        ),
        migrations.AlterField(
            model_name='reviewrecommender',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userdetail'),
        ),
    ]
