# Generated by Django 5.1.6 on 2025-02-24 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_alter_review_recommender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommender',
            field=models.ManyToManyField(blank=True, null=True, related_name='Review_recommender', through='review.ReviewRecommender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewrecommender',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
