# Generated by Django 5.1.6 on 2025-03-05 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_alter_review_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='priceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewTokenize', models.CharField(max_length=100)),
                ('PosNeg', models.IntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.review')),
            ],
        ),
    ]
