# Generated by Django 5.1.5 on 2025-03-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewImageUrl',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='review/'),
        ),
    ]
