# Generated by Django 5.1.4 on 2025-03-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0017_alter_review_reviewimageurl"),
        ("review", "0017_pricelog"),
    ]

    operations = []
