# Generated by Django 5.1.4 on 2025-03-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0018_merge_0017_alter_review_reviewimageurl_0017_pricelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelog",
            name="confidence",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TasteLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reviewTokenize", models.CharField(max_length=100)),
                ("PosNeg", models.IntegerField(default=0)),
                ("confidence", models.IntegerField(default=0)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="review.review"
                    ),
                ),
            ],
        ),
    ]
