# Generated by Django 4.2.20 on 2025-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0019_pricelog_confidence_tastelog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricelog",
            old_name="confidence",
            new_name="Confidence",
        ),
        migrations.RenameField(
            model_name="tastelog",
            old_name="confidence",
            new_name="Confidence",
        ),
        migrations.AlterField(
            model_name="pricelog",
            name="PosNeg",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pricelog",
            name="reviewTokenize",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tastelog",
            name="reviewTokenize",
            field=models.CharField(max_length=200),
        ),
    ]
