# Generated by Django 4.2.20 on 2025-03-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0020_rename_confidence_pricelog_confidence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelog",
            name="Confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="pricelog",
            name="PosNeg",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tastelog",
            name="Confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="tastelog",
            name="PosNeg",
            field=models.IntegerField(default=1),
        ),
    ]
