# Generated by Django 4.2.20 on 2025-03-13 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0022_conveniencelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasteKeywordLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reviewTokenize", models.CharField(max_length=200)),
                ("keybert_keywords", models.JSONField(default=list)),
                ("top_sim_tags", models.JSONField(default=list)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="review.review"
                    ),
                ),
            ],
        ),
    ]
