# Generated by Django 4.2.20 on 2025-03-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0023_tastekeywordlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="tastekeywordlog",
            name="sentence_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tastelog",
            name="sentence_id",
            field=models.IntegerField(default=0),
        ),
    ]
