# Generated by Django 5.1.6 on 2025-02-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userdetail_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='birthday',
            new_name='age_range',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='reward',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
