# Generated by Django 5.1.6 on 2025-02-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_birthday_userdetail_age_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='age_range',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
