# Generated by Django 5.1.6 on 2025-02-13 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategoryId',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productId',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='convenientStoreName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productImageUrl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='convenient_store_name',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='unknown', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productlikes',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
