# Generated by Django 5.1.6 on 2025-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('regi_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '게시물',
                'verbose_name_plural': '게시물',
                'db_table': 'board',
            },
        ),
    ]
